<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aeropuerto [
    <!ELEMENT aeropuerto (nombre, fecha, vuelos)>
        
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT fecha (#PCDATA)>
        
        <!ELEMENT vuelos (vuelo+)>
        
            <!ELEMENT vuelo (origen, destino, hora_salida, hora_llegada, compania, diario?)>
            <!ATTLIST vuelo codigo ID #REQUIRED>
            <!ATTLIST vuelo estado (C | E | R) "E">
        
            <!ELEMENT origen (#PCDATA)>
            <!ELEMENT destino (#PCDATA)>
            <!ELEMENT hora_salida (#PCDATA)>
            <!ELEMENT hora_llegada (#PCDATA)>
            <!ELEMENT compania (#PCDATA)>
            <!ELEMENT diario EMPTY>
]>

<!-- 
Nombre: Henry Leonardo Talavera Velasquez 
Curso: DAW1
Fecha: 2/4/2025 
Ejercicio: Ejercicio 3
-->

<aeropuerto>
    <nombre>Panel de vuelos de salida del jfk</nombre>
    <fecha>20/12/2013</fecha>
    <vuelos>
        <vuelo codigo="V22" estado="R">
            <origen>New York</origen>
            <destino>Chicago</destino>
            <hora_salida>9:30</hora_salida>
            <hora_llegada>11:30</hora_llegada>
            <diario/>
        </vuelo>
        <vuelo codigo="V23" estado="C">
            <origen>New York</origen>
            <destino>Miami</destino>
            <hora_salida>10:15</hora_salida>
            <hora_llegada>11:15</hora_llegada>
        </vuelo>
    </vuelos>
</aeropuerto>
