<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factura [
    <!ELEMENT factura (datos-emisor, datos-cliente, detalle-factura)>

        <!ATTLIST factura numero CDATA #REQUIRED>
        <!ATTLIST factura fecha CDATA #REQUIRED>

        <!ELEMENT datos-emisor (nombre, cif, telefono)>
        <!ELEMENT datos-cliente (nombre, cif, telefono)>

            <!ELEMENT nombre (#PCDATA)>
            <!ELEMENT cif (#PCDATA)>
            <!ELEMENT telefono (#PCDATA)>

        <!ELEMENT detalle-factura (linea+)>

            <!ATTLIST detalle-factura importe CDATA #REQUIRED>

            <!ELEMENT linea (descripcion, cantidad, pvp, oferta?)>

                <!ATTLIST linea codigo-articulo ID #REQUIRED>
                <!ATTLIST linea tipo (Libro | DVD | Varios) #REQUIRED>

                <!ELEMENT descripcion (#PCDATA)>
                <!ELEMENT cantidad (#PCDATA)>
                <!ELEMENT pvp (#PCDATA)>
                <!ELEMENT oferta EMPTY>
]>
<!-- 
Nombre: Henry Leonardo Talavera Velasquez 
Curso: DAW1
Fecha: 31/3/2025 
Ejercicio: Ejercicio 1 
-->
<factura numero="1" fecha="2025-03-31">
    <datos-emisor>
        <nombre>Libreria A</nombre>
        <cif>A12345678</cif>
        <telefono>123123123</telefono>
    </datos-emisor>
    <datos-cliente>
        <nombre>Biblioteca C</nombre>
        <cif>B12345678</cif>
        <telefono>456456456</telefono>
    </datos-cliente>
    <detalle-factura importe="15.00">
        <linea codigo-articulo="A01" tipo="Libro">
            <descripcion>El Principito</descripcion>
            <cantidad>1</cantidad>
            <pvp>15.00</pvp>
        </linea>
    </detalle-factura>
</factura>